name: Build and Deploy
on:
  push:
    # NOTE:
    #   For a **project** site (username.github.io/project/), push things
    #     to the **master** branch and make sure to set the line below to
    # `   - master`; also, at the end of the file, change to `BRANCH: gh-pages`
    #
    #   For a **personal** site (username.github.io/), push things to a **dev**
    #     branch  and make sure to set the line  below to `- dev` this is
    #     because for user pages GitHub pages **requires** the deployment to be
    #     on the master branch; also, at the end of the file, change to
    #    `BRANCH: master`
    branches:
      - source
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Install SSH Client
      continue-on-error: true
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.JEKYLL_PRIV }}
    # Use GitHub Actions' cache to shorten build times and decrease load on servers
    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - name: Run Jekyll
      uses:  lemonarc/jekyll-action@1.0.0
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        # NOTE
        #   Set this to `BRANCH: gh-pages` for a **project** page and  to
        #   `BRANCH: master` for a **personal** page
        BRANCH: master
        FOLDER: _site